### ISSUE TITLE
protected attributes

### ISSUE THREAD

**Issue by jmrenouard** [jfp/play-search#13]
Hello,

Is it possible to modify the accessibility of attributes in several class in order to be able to inherit and values the behaviour without having to copy/paste the full code.

In Query:

 private Class<JPABase> clazz;

```
private String query;

private Store store;

private String[] order = new String[0];

private int offset = 0;

private int pageSize = 10;

private boolean reverse = false;

private Hits hits = null;
```

in FileSystemStore:
  private Map<String, IndexWriter> indexWriters = new HashMap<String, IndexWriter>();

```
private Map<String, IndexSearcher> indexSearchers = new HashMap<String, IndexSearcher>();
```

BR,
Jean-Marie Renouard

**Comment by jfp** [comment]
Hi,

Those were intended to be implementation (IE private). Changing them to public will reduce the usability of the API, however if you have good reasons, we'll change this. What do you want to do you can't do with the actual API ?

**Comment by jmrenouard** [comment]
Hello,

Scoring Lucene is working badly sometimes.

We need to upgrade to lucene 3.0.3 logically.
The current class needed to be updated in this case are:
Query
ConversionUtils
FileSystemStore

In the API himself, maybe it would be sympathic to include a stat methods.
- Number of document per index
- Size of each index
- request method allowing directly to fetch objet for a search
  List<?> searchElement( String request, int maxRes, Class entityClass);
  Perform lucene request returning maxRes object of entityClass
  public List<?> searchElements(String request, int maxElement,
          String orderBy, Class clazz) {
      String trueRequest=request.trim();
  
  ```
  if ("".equals(trueRequest)) {
      return new ArrayList<JPABase>();
  }
  Query q = Search.search(request, clazz);
  if (orderBy !="") {
      q.orderBy(orderBy);
  }
  if (maxElement!= -1) {
      q.page(0, maxElement);
  }
  return q.fetch();
  ```
  
  }

In the same way as the crud module, having a controller with the big work around managing index with simple link allowing : full reindex, optimze, info on index eventually read/write count and some indicator calculation in a single view could be very nice.

I already saw a basic controller for that but it doesn't seem to be integrated in the module search.

Last point, we need more tools to remove accents in french language during the indexation process AND during the search/read process too.
The current API can't help anybody to add to the analyser/store and query any class
 helping to custome his indexing and reading process.

In this case, we need a Filter generic API with addFilter on store or query.

That's all Folks for the moment on this module.

The hardest work is done and we just need improve this module to be at this best and sharpen it to be very pro.

Bye,
Jean-Marie Renouard
