### ISSUE TITLE
[Patch] Allow to change the default search field.

### ISSUE THREAD

**Issue by sebfroh** [jfp/play-search#23]
diff --git a/src/play/modules/search/Query.java b/src/play/modules/search/Query.java
index 37ddce4..2acad2c 100644
--- a/src/play/modules/search/Query.java
+++ b/src/play/modules/search/Query.java
@@ -146,8 +146,9 @@ public class Query {
     public List<QueryResult> executeQuery(boolean fetch) throws SearchException {
         try {
             if (topDocs == null) {
-                String field = Play.configuration.getProperty("play.search.defaultSearchField", "allfield");
               org.apache.lucene.search.Query luceneQuery =
-                                new QueryParser(Search.getLuceneVersion(), "_docID", Search.getAnalyser()).parse(query);
-                                new QueryParser(Search.getLuceneVersion(), field, Search.getAnalyser()).parse(query);
               BooleanQuery.setMaxClauseCount(Integer.parseInt(Play.configuration.getProperty(
                               "play.search.maxClauseCount", "1024")));
               topDocs = indexSearcher.search(luceneQuery, null, Integer.MAX_VALUE, getSort());

**Comment by jfp** [comment]
Integrated in cf1d5c3508af53fe07038af1a5d2c28d50746bec
