### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by ultraflynn** [jfp/play-search#25]
I know the password for the admin console is "search", but what is the username?

**Comment by sgodbillon** [comment]
By reading the code, it does not matter.
You have to enter a random username, then the right password and it's ok.

**Comment by ultraflynn** [comment]
That was my reading too so I must have a different problem because it doesn't matter what I enter as a username I can never get valid credentials. I've had to give up using the module for now. I'll try again another time.

Thanks for the response.

**Comment by jfp** [comment]
Hi,

What is your browser's behaviour when you type search as password and validate the http auth ?

**Comment by ultraflynn** [comment]
I literally just get a blank screen. I've tried this on Chrome and IE7. Same result.

It's odd actually. I'm wondering whether it's something to do with the the corporate authentication we have but it's difficult to see how as I'm running locally.

**Comment by jfp** [comment]
Hello,

That's weird. Maybe you can try to setup your browsers so that they do not use proxy localhost ?

Anyway, in the latest head release, you can add this conf :
play.search.auth.method=session

So that the console will use session based authentication.
