### ISSUE TITLE
Index for OneToOne or ManyToOne property

### ISSUE THREAD

**Issue by mechiland** [jfp/play-search#6]
Thanks for you great effort first! 

We found a scenario that some times we need to support ManyToOne indexing. For example, one User has many Articles. So the Article model would be like: 

```
@ManyToOne @Field
public User user;
@Field
public String title
```

So If I want to search like "title:title AND user:Someoen", it will give me like "title:title AND user:User[1]" because of the current ConversionUtils impl, which Lucene doesn't like it, and the Model.toString() is very likely to be overridden. 

If you could understand this problem and/or fix this with a smater way that will be great. FYI, I provide my simple patch here(github deesnot support attachment...)

```
diff --git a/src/play/modules/search/store/ConvertionUtils.java b/src/play/modules/search/store/ConvertionUtils.java
index 20d2d7b..d39e966 100644
--- a/src/play/modules/search/store/ConvertionUtils.java
+++ b/src/play/modules/search/store/ConvertionUtils.java
@@ -86,6 +86,10 @@ public class ConvertionUtils {
        if (field.getType().equals(FileAttachment.class) && field.get(object)!= null) {
            return FileExtractor.getText((FileAttachment) field.get(object));
        }
+       Object o = field.get(object);
+       if (o instanceof JPASupport) {
+           return "" + getIdValueFor(o); 
+       }
        return "" + field.get(object);
    }
```

**Comment by jfp** [comment]
Hi, 

Your patch is in c6f5664bc6c775a3c057, thank you ! I've added so more checks in 5fea37b39ff3b5133f3c, is it better ?

Regarding smarter things... Maybe what you want to do is no directly fetch JPAObjects, but rather a list of ids ordered by relevance, (fetchIds) and then use them in a JPA query where you can do your domain filtering ?

**Comment by mechiland** [comment]
I saw your changes. It looks good. however, I guess you need to add OneToOne as well.
